# Generated by Django 5.1.7 on 2025-03-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concept_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='label',
        ),
        migrations.AddField(
            model_name='concept',
            name='x_pos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='concept',
            name='y_pos',
            field=models.FloatField(default=0.0),
        ),
    ]
